### ISSUE TITLE
Announce Address uses port 5678 -- Should be 3919

### ISSUE THREAD

**Issue by willtate** [afmsavage/keep-ecdsa-tf#1]
Great work! I think I spotted a potential issue though.

https://github.com/afmsavage/keep-ecdsa-tf/blob/master/user_data.sh#L67

Announce port should be 3919 as well as 5678 isn't open in the security policy or forwarded to the docker container in any way?

**Comment by afmsavage** [comment]
I can add 5678 to the securitygroups config.  I was unaware that it needed to be open.  Since it's outbound only (I think), it should be allowed in the catchall of ANY -> 0.0.0.0/0 on outbound traffic.  I -think- 3919 is only needed as inbound.  I will do some digging and update.
